version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend-container
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    networks:
      - my-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
